# Phase 2 Review

In [3]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from statsmodels.formula.api import ols

pd.set_option('display.max_columns', 100)

In [84]:
from scipy import stats
import math

### Check Your Data … Quickly
The first thing you want to do when you get a new dataset, is to quickly to verify the contents with the .head() method.

In [133]:
df['genres'].value_counts()

Drama                                     236
Comedy                                    209
Comedy|Drama                              191
Comedy|Drama|Romance                      187
Comedy|Romance                            158
                                         ...
Adventure|Family|Sci-Fi                     1
Comedy|Crime|Drama|Sci-Fi                   1
Biography|Comedy|Drama|History|Music        1
Action|Adventure|Comedy|Crime|Thriller      1
Action|Drama|History|Thriller|War           1
Name: genres, Length: 914, dtype: int64

In [4]:
df = pd.read_csv('movie_metadata.csv')
print(df.shape)
df.head()

(5043, 28)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,4834,Wes Studi,0.0,avatar|future|marine|native|paraplegic,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,48350,Jack Davenport,0.0,goddess|marriage ceremony|marriage proposal|pi...,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,11700,Stephanie Sigman,1.0,bomb|espionage|sequel|spy|terrorist,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,106759,Joseph Gordon-Levitt,0.0,deception|imprisonment|lawlessness|police offi...,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,Doug Walker,Star Wars: Episode VII - The Force Awakens ...,8,143,NaN,0.0,NaN,http://www.imdb.com/title/tt5289954/?ref_=fn_t...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

## Question 1

A Hollywood executive wants to know how much an R-rated movie released after 2000 will earn. The data above is a sample of some of the movies with that rating during that timeframe, as well as other movies. How would you go about answering her question? Talk through it theoretically and then do it in code.

What is the 95% confidence interval for a post-2000 R-rated movie's box office gross?

In [222]:
#Drop null values

In [ ]:
#We will first categorize our data into the necessary elements which would be:
    #R rated movies released after 2000. We will also remove movies that do not have their box office gross data from
    #consideration.
#We then utilize this subset to get the mean gross profits of that.
#We will then utilize our available data on gross profits to calculate a range that we expect
#a post 2000, R-rated movie's gross profit to full under.

In [ ]:
df.query("(content_rating == 'R') & (title_year > 2000)").dropna(subset=['gross'])
# another way to do it

In [ ]:
df[(df['title_year'] > 2000) & (df['content_rating'] == 'R')].dropna(subset = ['gross'])
# to drop the nas

In [221]:
mean

27648848.437913906

In [219]:
# 95% confidence interval
stats.t.interval(
        alpha = .05,
        df = len(df[(df['title_year'] > 2000) & (df['content_rating'] == 'R') & (df['gross'].isna() != True)]) - 1,
        loc = df[(df['title_year'] > 2000) & (df['content_rating'] == 'R')]['gross'].mean(),
        scale = df[(df['title_year'] > 2000) & (df['content_rating'] == 'R')]['gross'].std()
        )

(25197202.549191598, 30100494.326636214)

In [220]:
mean = df[(df['title_year'] > 2000) & (df['content_rating'] == 'R')]['gross'].mean()
std = df[(df['title_year'] > 2000) & (df['content_rating'] == 'R')]['gross'].std()
z = 1.96
n = len(df[(df['title_year'] > 2000) & (df['content_rating'] == 'R') & (df['gross'].isna() != True)]) - 1

lower = mean - (z*(std/math.sqrt(n)))
upper = mean + (z*(std/math.sqrt(n)))

lower, upper

(25443610.857692726, 29854086.018135086)

In [ ]:
# bottom of above equation is standard error.

## Question 2a

Your ability to answer the first question has the executive excited and now she has many other questions about the types of movies being made and the differences in those movies budgets and gross amounts.

Read through the questions below and **determine what type of statistical test you should use** for each question and **write down the null and alternative hypothesis for those tests**.

- Is there a relationship between the number of Facebook likes for a cast and the box office gross of the movie?

In [ ]:
# Test: correlation/simple linear regression
# It is two continuous variables so we can't use the other two sample data. We don't have
# categorical data to split into the two separate categories.

#Null: There is no relationship between the number of Facebook likes for a cast
    # and the box office gross of the movie?
#Alternative: There is a relationship between the number of Facebook likes for a cast
    # and the box office gross of the movie?

- Do foreign films perform differently at the box office than non-foreign films?

In [77]:
# Test: Two sided t-test because difference between two means

# Null: The box office gross of foreign films perform similarly 
    # to non-foreign films.
# Null: The box office gross of foreign films perform differently 
    # to non-foreign films.
    
# Is th

Ttest_indResult(statistic=-12.098302287742106, pvalue=3.863109466861356e-33)

- Of all movies created are 40% rated R?

In [118]:
# Z test for Proportion

# Null: Proportion of r rated movies is equal to .4
# Alternative: Proportion of r rated movies is not equal to .4

p_hat = df['content_rating'].value_counts(normalize = True)[0]
p_0 = .40
n = len(df[df['content_rating'].isna() != True])

(p_hat - p_0)/math.sqrt((p_0 * (1 - p_0))/n)

# 40% of all movies created are not rated R.
# When tested, the test statistic returns 6.58, far larger than our positive confidence interval point of 1.96.

6.582004619424582

- Is there a relationship between the language of a film and the content rating (G, PG, PG-13, R) of that film?

In [ ]:
# Chi Squared (qualitative data), (categorical variables). They also have multiple variables

# Null:
    # Are these multiple distributions the same? Distributions are equal.
# Alternative: They are not

- Is there a relationship between the content rating of a film and its budget?

In [177]:
# ANOVA
# It's quantitative data so it's ANOVA. Ratings are categorical, but budget is quantitative, or continuous. 

# Null: Distributions are equal
# Alternative: They are not equal.

## Question 2b

Calculate the answer for the second question:

- Do foreign films perform differently at the box office than non-foreign films?

In [ ]:
# above there is no notice of what significance level you use.
# always want to set the level of significance before the test

In [224]:
len(df[df['country'] == 'USA']['gross'].dropna().values)

3235

In [185]:
len(df[(df['country'] == 'USA') & (df['gross'].isna() != True)]['gross'].values)

3235

In [230]:
# Null: Foreign films perform similarly at the box office when compared to non-foreign films.
# Alternative: Foreign films perform differently at the box office when compared to non-foreign films.

foreign_films = df[df['country'] != 'USA']['gross'].dropna().values
domestic_films = df[df['country'] == 'USA']['gross'].dropna().values
stats.ttest_ind(foreign_films, domestic_films)

# Foreign films do perform differently at the box offic when compared to domestic films.
# The pvalue of 3.86e-33 is smaller than our alpha of .05 which means we reject the null hypothesis.

Ttest_indResult(statistic=-12.098302287742106, pvalue=3.863109466861356e-33)

In [229]:
foreign_films = df[df['country'] != 'USA']['gross'].values
domestic_films = df[df['country'] == 'USA']['gross'].values
stats.ttest_ind(foreign_films, domestic_films, nan_policy = 'omit')

Ttest_indResult(statistic=-12.098302287742106, pvalue=3.8631094668570096e-33)

## Question 3

Now that you have answered all of those questions, the executive wants you to create a model that predicts the money a movie will make if it is released next year in the US. She wants to use this to evaluate different scripts and then decide which one has the largest revenue potential. 

Below is a list of potential features you could use in the model. Would you use all of these features in the model? Identify which features you might drop and why.


*Remember you want to be able to use this model to predict the box office gross of a film **before** anyone has seen it.*

- **budget**: The amount of money spent to make the movie
- **title_year**: The year the movie first came out in the box office
- **years_old**: How long has it been since the movie was released
- **genre**: Each movie is assigned one genre category like action, horror, comedy
- **avg_user_rating**: This rating is taken from Rotten tomatoes, and is the average rating given to the movie by the audience
- **actor_1_facebook_likes**: The number of likes that the most popular actor in the movie has
- **total_cast_facebook_likes**: The sum of likes for the three most popular actors in the movie
- **language**: the original spoken language of the film

In [135]:
df

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,years_old
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,4834,Wes Studi,0.0,avatar|future|marine|native|paraplegic,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000,12.0
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,48350,Jack Davenport,0.0,goddess|marriage ceremony|marriage proposal|pi...,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0,14.0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,11700,Stephanie Sigman,1.0,bomb|espionage|sequel|spy|terrorist,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000,6.0
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,106759,Joseph Gordon-Levitt,0.0,deception|imprisonment|lawlessness|police offi...,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000,9.0
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,Doug Walker,Star Wars: Episode VII - The Force Awakens ...,8,143,NaN,0.0,NaN,http://www.imdb.com/title/tt5289954/?ref_=fn_t...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,Eric Mabius,Signed Sealed Delivered,629,2283,Crystal Lowe,2.0,fraud|postal worker|prison|theft|trial,http://www.imdb.com/title/tt3000844/?ref_=fn_t...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84,8.0
5039,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,Natalie Zea,The Following,73839,1753,Sam Underwood,1.0,cult|fbi|hideout|prison escape|serial killer,http://www.imdb.com/title/tt2071645/?ref_=fn_t...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000,NaN
5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,Eva Boehnke,A Plague So Pleasant,38,0,David Chandler,0.0,NaN,http://www.imdb.com/title/tt2107644/?ref_=fn_t...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16,8.0
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,Alan Ruck,Shanghai Calling,1255,2386,Eliza Coupe,5.0,NaN,http://www.imdb.com/title/tt2070597/?ref_=fn_t...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660,9.0
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,John August,My Date with Drew,4285,163,Jon Gunn,0.0,actress name in title|crush|date|four word tit...,http://www.imdb.com/title/tt0378407/?ref_=fn_t...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456,17.0

In [128]:
df['years_old'] = np.where(df['title_year'].isna() != True, 2021 - df['title_year'], np.nan)

In [192]:
df['genres'].value_counts()

Drama                                     236
Comedy                                    209
Comedy|Drama                              191
Comedy|Drama|Romance                      187
Comedy|Romance                            158
                                         ...
Adventure|Family|Sci-Fi                     1
Comedy|Crime|Drama|Sci-Fi                   1
Biography|Comedy|Drama|History|Music        1
Action|Adventure|Comedy|Crime|Thriller      1
Action|Drama|History|Thriller|War           1
Name: genres, Length: 914, dtype: int64

In [233]:
df.genres.apply(lambda x: x.split('|')[0])

0            Action
1            Action
2            Action
3            Action
4       Documentary
           ...
5038         Comedy
5039          Crime
5040          Drama
5041         Comedy
5042    Documentary
Name: genres, Length: 5043, dtype: object

In [193]:
df['language'].value_counts()

English       4704
French          73
Spanish         40
Hindi           28
Mandarin        26
German          19
Japanese        18
Russian         11
Cantonese       11
Italian         11
Korean           8
Portuguese       8
Hebrew           5
Swedish          5
Danish           5
Arabic           5
Polish           4
Persian          4
Dutch            4
Norwegian        4
Chinese          3
Thai             3
Aboriginal       2
None             2
Romanian         2
Zulu             2
Indonesian       2
Icelandic        2
Dari             2
Panjabi          1
Slovenian        1
Kannada          1
Bosnian          1
Greek            1
Urdu             1
Vietnamese       1
Mongolian        1
Kazakh           1
Maya             1
Swahili          1
Aramaic          1
Filipino         1
Hungarian        1
Czech            1
Tamil            1
Dzongkha         1
Telugu           1
Name: language, dtype: int64

In [144]:
# asking if you should remove any of these features. What's one way to check?
# check if any of the correlations between them are very high. Sean .9, Greg .7
    # looking for multi coliniarity

df[['budget', 'title_year', 'years_old',
    'genres', 'imdb_score', 'actor_1_facebook_likes',
    'cast_total_facebook_likes', 'language']].corr()

#actor_1_facebook_likes because of correlation with cast_total_facebook_likes.
#title_year because of correlation with years_old

#theoretically it doesn't matter which one you drop. Since their correlation is so similar
    #their effect is basically the same. Later though you can find out which one to choose. Future lecture

#imdb_score because this is BEFORE anyone has seen it, not after and already rating it
#language because of the it will be released in the US, so likely English
#genres because individual movies have multiple genres
    #therefore we would not know which genre in particular created an effect on the movie
    #they're weight is unknown.
    #they're alphabetical so you can't just pull the first one.

,budget,title_year,years_old,imdb_score,actor_1_facebook_likes,cast_total_facebook_likes
budget,1.000000,0.045726,-0.045726,0.030688,0.022639,0.036557
title_year,0.045726,1.000000,-1.000000,-0.209167,0.086873,0.109971
years_old,-0.045726,-1.000000,1.000000,0.209167,-0.086873,-0.109971
imdb_score,0.030688,-0.209167,0.209167,1.000000,0.076099,0.085787
actor_1_facebook_likes,0.022639,0.086873,-0.086873,0.076099,1.000000,0.951661
cast_total_facebook_likes,0.036557,0.109971,-0.109971,0.085787,0.951661,1.000000

## Question 4a

Create the following variables:

- `years_old`: The number of years since the film was released.
- Dummy categories for each of the following ratings:
    - `G`
    - `PG`
    - `R`
    
Once you have those variables, create a summary output for the following OLS model:

`gross~cast_total_facebook_likes+budget+years_old+G+PG+R`

In [158]:
ratings_df = pd.get_dummies(df[df['content_rating'].isin(['R', 'PG', 'G'])]['content_rating'])
ratings_df

      G  PG  R
7     0   1  0
9     0   1  0
16    0   1  0
33    0   1  0
35    1   0  0
...  ..  .. ..
5019  0   0  1
5021  0   0  1
5026  0   0  1
5035  0   0  1
5042  0   1  0

[2931 rows x 3 columns]

In [ ]:
# since you can infer one of them from the others, it can lead to colinearity

In [194]:
final_df = ratings_df.join(df)
final_df

,G,PG,R,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,years_old
7,0,1,0,Color,Nathan Greno,324.0,100.0,15.0,284.0,Donna Murphy,799.0,200807262.0,Adventure|Animation|Comedy|Family|Fantasy|Musi...,Brad Garrett,Tangled,294810,2036,M.C. Gainey,1.0,17th century|based on fairy tale|disney|flower...,http://www.imdb.com/title/tt0398286/?ref_=fn_t...,387.0,English,USA,PG,260000000.0,2010.0,553.0,7.8,1.85,29000,11.0
9,0,1,0,Color,David Yates,375.0,153.0,282.0,10000.0,Daniel Radcliffe,25000.0,301956980.0,Adventure|Family|Fantasy|Mystery,Alan Rickman,Harry Potter and the Half-Blood Prince,321795,58753,Rupert Grint,3.0,blood|book|love|potion|professor,http://www.imdb.com/title/tt0417741/?ref_=fn_t...,973.0,English,UK,PG,250000000.0,2009.0,11000.0,7.5,2.35,10000,12.0
16,0,1,0,Color,Andrew Adamson,258.0,150.0,80.0,201.0,Pierfrancesco Favino,22000.0,141614023.0,Action|Adventure|Family|Fantasy,Peter Dinklage,The Chronicles of Narnia: Prince Caspian,149922,22697,Damián Alcázar,4.0,brother brother relationship|brother sister re...,http://www.imdb.com/title/tt0499448/?ref_=fn_t...,438.0,English,USA,PG,225000000.0,2008.0,216.0,6.6,2.35,0,13.0
33,0,1,0,Color,Tim Burton,451.0,108.0,13000.0,11000.0,Alan Rickman,40000.0,334185206.0,Adventure|Family|Fantasy,Johnny Depp,Alice in Wonderland,306320,79957,Anne Hathaway,0.0,alice in wonderland|mistaking reality for drea...,http://www.imdb.com/title/tt1014759/?ref_=fn_t...,736.0,English,USA,PG,200000000.0,2010.0,25000.0,6.5,1.85,24000,11.0
35,1,0,0,Color,Dan Scanlon,376.0,104.0,37.0,760.0,Tyler Labine,12000.0,268488329.0,Adventure|Animation|Comedy|Family|Fantasy,Steve Buscemi,Monsters University,235025,14863,Sean Hayes,0.0,cheating|fraternity|monster|singing in a car|u...,http://www.imdb.com/title/tt1453405/?ref_=fn_t...,265.0,English,USA,G,200000000.0,2013.0,779.0,7.3,1.85,44000,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5019,0,0,1,Color,Marcus Nispel,43.0,91.0,158.0,265.0,Brittany Curran,630.0,NaN,Horror|Mystery|Thriller,Ashley Tramonte,Exeter,3836,2679,Lindsay MacDonald,0.0,asylum|demon|party|secret|teenager,http://www.imdb.com/title/tt1945044/?ref_=fn_t...,33.0,English,USA,R,NaN,2015.0,512.0,4.6,1.85,0,6.0
5021,0,0,1,Color,Jay Duplass,51.0,85.0,157.0,10.0,Katie Aselton,830.0,192467.0,Comedy|Drama|Romance,Mark Duplass,The Puffy Chair,4067,1064,Bari Hyman,0.0,birthday|gift|motel|new york city|upholsterer,http://www.imdb.com/title/tt0436689/?ref_=fn_t...,71.0,English,USA,R,15000.0,2005.0,224.0,6.6,NaN,297,16.0
5026,0,0,1,Color,Olivier Assayas,81.0,110.0,107.0,45.0,Béatrice Dalle,576.0,136007.0,Drama|Music|Romance,Maggie Cheung,Clean,3924,776,Don McKellar,1.0,jail|junkie|money|motel|singer,http://www.imdb.com/title/tt0388838/?ref_=fn_t...,39.0,French,France,R,4500.0,2004.0,133.0,6.9,2.35,171,17.0
5035,0,0,1,Color,Robert Rodriguez,56.0,81.0,0.0,6.0,Peter Marquardt,121.0,2040920.0,Action|Crime|Drama|Romance|Thriller,Carlos Gallardo,El Mariachi,52055,147,Consuelo Gómez,0.0,assassin|death|guitar|gun|mariachi,http://www.imdb.com/title/tt0104815/?ref_=fn_t...,130.0,Spanish,USA,R,7000.0,1992.0,20.0,6.9,1.37,0,29.0
5042,0,1,0,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,John August,My Date with Drew,4285,163,Jon Gunn,0.0,actress name in title|crush|date|four word tit...,http://www.imdb.com/title/tt0378407/?ref_=fn_t...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456,17.0

In [195]:
# your answer here
mlr_model = ols(formula = 'gross ~ cast_total_facebook_likes+budget+years_old+G+PG+R', data = final_df).fit()
mlr_model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  gross   R-squared:                       0.162
Model:                            OLS   Adj. R-squared:                  0.160
Method:                 Least Squares   F-statistic:                     92.43
Date:                Wed, 26 May 2021   Prob (F-statistic):           3.43e-89
Time:                        14:07:23   Log-Likelihood:                -46224.
No. Observations:                2404   AIC:                         9.246e+04
Df Residuals:                    2398   BIC:                         9.249e+04
Df Model:                           5
Covariance Type:            nonrobust
=============================================================================================
                                coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------
Intercept                  4.138e+07    2.5e+06     16.553      0.000    3.65e+07    4.63e+07
cast_total_facebook_likes   784.8777     73.740     10.644      0.000     640.277     929.478
budget                        0.0091      0.004      2.229      0.026       0.001       0.017
years_old                  6.083e+04   1.19e+05      0.510      0.610   -1.73e+05    2.95e+05
G                          3.642e+07   4.43e+06      8.219      0.000    2.77e+07    4.51e+07
PG                         2.464e+07   2.32e+06     10.627      0.000    2.01e+07    2.92e+07
R                         -1.968e+07   1.88e+06    -10.473      0.000   -2.34e+07    -1.6e+07
==============================================================================
Omnibus:                     1297.450   Durbin-Watson:                   1.164
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            11583.710
Skew:                           2.409   Prob(JB):                         0.00
Kurtosis:                      12.614   Cond. No.                     1.61e+24
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 7.01e-29. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [ ]:
# realize that there's two different ways. know how to use one of them.
# next week you'll be using scikitlearn rather than statsmodels. scikitlearn uses the x and y variable
    #

## Question 4b

Below is the summary output you should have gotten above. Identify any key takeaways from it.
- How ‘good’ is this model?
- Which features help to explain the variance in the target variable? 
    - Which do not?

<img src="ols_summary.png" style="withd:300px;">

In [ ]:
# your answer here
# This model is not very accurate. The Rsquared value is 0.079 and the adj. r-squared is .075
# These are far in distance from 1, meaning they are quite inaccurate.
# It only explains .08 of the variance.
#
# The variables with a p value under the level of significance (say 95%) are helpful.
# The G rating predictor may not be as helpful due to it's p value of .150.


# The coefficient for budget means that for each change in unit for budget, there will be that
# much of a change in gross. So 1 unit increase in budget = 4.2 million change in gross
# budget is not in dollars. What is the unit for it? standard deviation.

#However, if variables are on different scales, its hard to grade by coefficient.
#that is why people normalize data. In the image he standardized them.

In [ ]:
# what does coefficient for PG mean?
# if g == 0, pg == 0, r == 0, then that means you have a pg13 movies.

# so if movie was PG you'd be making 13.6 more than if your movie was rated pg13
# a PG would make about 3 more than a G because you'd be subtracting the coefficients

# so with dummy variables, you're interpreting against the one you dropped.
# this is not on the assessment

## Question 5

**Bayes Theorem**

An advertising executive is studying television viewing habits of married men and women during prime time hours. Based on the past viewing records he has determined that during prime time wives are watching television 60% of the time. It has also been determined that when the wife is watching television, 40% of the time the husband is also watching. When the wife is not watching the television, 30% of the time the husband is watching the television. Find the probability that if the husband is watching the television, the wife is also watching the television.

In [191]:
p_women_watch = .6
p_women_not_watch = 1 - p_women_watch

p_men_watch = (p_men_watch_given_women_watch*p_women_watch)\
            + (p_men_watch_given_women_notwatch*p_women_not_watch)

p_men_watch_given_women_watch = .4
p_men_watch_given_women_notwatch = .3


#what is:
p_women_watch_given_men_watch =\
(p_men_watch_given_women_watch * p_women_watch)/p_men_watch

p_women_watch_given_men_watch

0.6666666666666666

## Question 6

Explain what a Type I error is and how it relates to the significance level when doing a statistical test.

In [ ]:
# A type 1 error is a false positive and occurs when we reject the null hypothesis even though we should have
# failed to reject the null hypothesis. By random chance we may end up finding an effect where one doesn't exist
# We expect these when we perform many tests when there is no effect.
# The significance level, alpha, is the level we set, generally between 1-5%, that defines
# our tolerance for a type 1 error. If our p value, or probability of the statistical test
# being true, is less than that error tolerance we reject the null hypothesis because
# the chance of it occuring is so low it is likely false.

# so if our significance level is 95%, what does type 1 error mean.
    # means 5% chance of making a Type 1 Error

## Question 7

How is the confidence interval for a sample related to a one sample t-test?

In [ ]:
# think of this as a bonus. Another level of understanding that will not be explicitly asked
# on the assessment. But try to be able to answer it.

In [ ]:
#your answer here